# Generated by Django 3.0.4 on 2020-03-21 20:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('virtual_location', models.CharField(max_length=50)),
                ('current_capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('max_capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('features', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='toys',
        ),
        migrations.DeleteModel(
            name='Toy',
        ),
        migrations.AddField(
            model_name='pet',
            name='playground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Playground'),
        ),
    ]
