# Generated by Django 3.0.4 on 2020-03-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200321_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='playground',
        ),
        migrations.AddField(
            model_name='pet',
            name='playgrounds',
            field=models.ManyToManyField(to='main_app.Playground'),
        ),
    ]
