# Generated by Django 3.0.4 on 2020-03-22 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200322_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='playgrounds',
            field=models.ManyToManyField(blank=True, to='main_app.Playground'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='current_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='playground',
            name='max_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
