# Generated by Django 3.0.4 on 2020-03-22 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20200322_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='playgrounds',
            field=models.ManyToManyField(blank=True, related_name='pets', to='main_app.Playground'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
