# Generated by Django 3.0.4 on 2020-03-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200322_2155'),
        ('main_app', '0007_auto_20200323_0115'),
    ]

    operations = [
    ]
