# Generated by Django 3.0.4 on 2020-03-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20200323_0639'),
        ('main_app', '0008_merge_20200323_1705'),
    ]

    operations = [
    ]
