# Generated by Django 3.0.4 on 2020-03-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20200323_2249'),
        ('main_app', '0009_merge_20200323_2315'),
    ]

    operations = [
    ]
