# Generated by Django 3.0.4 on 2020-03-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20200324_0200'),
        ('main_app', '0010_merge_20200324_0240'),
    ]

    operations = [
    ]
