# Generated by Django 3.0.4 on 2020-03-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200319_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
