# Generated by Django 3.0.4 on 2020-03-20 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_pet_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toy',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='toy',
            name='material',
            field=models.CharField(max_length=20),
        ),
    ]
